# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 17:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MiUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100, null=True)),
                ('video', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.MiUsuario')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.MiUsuario'),
        ),
        migrations.AddField(
            model_name='follow',
            name='usuario_sigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ususario_sigo', to='instagramapp.MiUsuario'),
        ),
        migrations.AddField(
            model_name='follow',
            name='usuario_sigue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_usuario_sigue', to='instagramapp.MiUsuario'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.MiUsuario'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.Post'),
        ),
    ]
