# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_auto_20170527_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='creador',
        ),
    ]
